"""Generate README auto-generated sections through the unified output layer.

This script inspects the notebooks and output artefacts already produced by
the notebooks and can do two things:

1. Write markdown fragments to ``output/readme/`` via
   :class:`src.output_manager.OutputManager` (side-effect free, never touches
   ``README.md``).
2. Safely replace the content between ``<!-- BEGIN auto-generated … -->``
   and ``<!-- END auto-generated -->`` markers inside ``README.md`` itself,
   without disturbing any other sections.

Use mode (1) for CI / previews.  Use mode (2) — :func:`update_readme_in_place`
— when you want the repo root ``README.md`` to stay up-to-date.

Run from the repo root::

    # Generate fragments only (default)
    python -m src.generate_readme_section

    # Safe in-place update of README.md
    python -m src.generate_readme_section --in-place

    # Dry run (print what would change)
    python -m src.generate_readme_section --in-place --dry-run
"""

from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable, Optional, Union

from data_paths import CODE_DIR, REPO_ROOT

from src.output_manager import (
    OutputManager,
    OverwritePolicy,
    WriteRecord,
    get_output_manager,
)


PathLike = Union[str, Path]


# --------------------------------------------------------------------------- #
# Scanners
# --------------------------------------------------------------------------- #
def _iter_notebooks(root: PathLike = CODE_DIR) -> Iterable[Path]:
    root = Path(root)
    for p in sorted(root.glob("ch*-exercise-*.ipynb")):
        if p.is_file():
            yield p


def _extract_title(nb_path: Path) -> Optional[str]:
    try:
        with open(nb_path, encoding="utf-8") as f:
            nb = json.load(f)
    except (OSError, json.JSONDecodeError):
        return None
    for cell in nb.get("cells", []):
        if cell.get("cell_type") != "markdown":
            continue
        src = "".join(cell.get("source", []))
        for line in src.splitlines():
            stripped = line.strip()
            if stripped.startswith("#"):
                return stripped.lstrip("#").strip()
        if src.strip():
            return src.strip().splitlines()[0][:80]
    return None


def _collect_artefacts(output_root: PathLike) -> dict[str, list[Path]]:
    output_root = Path(output_root)
    groups: dict[str, list[Path]] = {}
    if not output_root.exists():
        return groups
    for category in ("altair", "plotly", "notebook", "readme"):
        cat_dir = output_root / category
        if not cat_dir.is_dir():
            continue
        groups[category] = sorted(p for p in cat_dir.rglob("*") if p.is_file())
    return groups


# --------------------------------------------------------------------------- #
# Section builders
# --------------------------------------------------------------------------- #
def build_notebook_index() -> str:
    lines: list[str] = []
    lines.append("## Notebooks")
    lines.append("")
    lines.append("<!-- auto-generated by src.generate_readme_section -->")
    lines.append("")
    for nb in _iter_notebooks():
        title = _extract_title(nb) or nb.stem
        rel = nb.relative_to(REPO_ROOT)
        lines.append(f"- [{title}]({rel.as_posix()})")
    lines.append("")
    return "\n".join(lines)


def build_artefact_index(output_root: PathLike) -> str:
    groups = _collect_artefacts(output_root)
    lines: list[str] = []
    lines.append("## Output artefacts")
    lines.append("")
    lines.append("<!-- auto-generated by src.generate_readme_section -->")
    lines.append("")
    if not any(groups.values()):
        lines.append("_No artefacts have been generated yet — run the notebooks to populate._")
        lines.append("")
        return "\n".join(lines)
    for category in ("altair", "plotly", "notebook", "readme"):
        files = groups.get(category, [])
        if not files:
            continue
        lines.append(f"### {category.title()}")
        lines.append("")
        for p in files:
            rel = p.relative_to(output_root if Path(output_root).exists() else REPO_ROOT)
            lines.append(f"- `{rel.as_posix()}`")
        lines.append("")
    return "\n".join(lines)


def build_header(
    generator: str = "src.generate_readme_section",
    section: Optional[str] = None,
) -> str:
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    tag = f" section={section}" if section else ""
    return (
        f"<!-- BEGIN auto-generated by {generator}{tag} at {ts} -->\n"
        f"<!-- Do not edit this block manually — regenerate with `python -m src.generate_readme_section` -->\n"
    )


def build_footer(section: Optional[str] = None) -> str:
    tag = f" section={section}" if section else ""
    return f"<!-- END auto-generated{tag} -->\n"


# --------------------------------------------------------------------------- #
# In-place README update (safe marker replacement)
# --------------------------------------------------------------------------- #
def _replace_marked_block(
    text: str,
    new_block: str,
    *,
    section: Optional[str] = None,
) -> tuple[str, bool]:
    """Replace the first ``BEGIN…END`` block in *text* with *new_block*.

    Matching is tolerant:
    - ``section`` is optional and only used to disambiguate multiple blocks.
    - The header regex accepts any timestamp/generator string.
    - Lines between header and footer are removed; the markers themselves
      are replaced with *new_block* (which already carries its own markers).
    """
    if section:
        header_re = re.compile(
            r"<!--\s*BEGIN\s+auto-generated[^>]*\s+section="
            + re.escape(section)
            + r"\b[^>]*-->",
        )
        footer_re = re.compile(
            r"<!--\s*END\s+auto-generated\s+section="
            + re.escape(section)
            + r"\b[^>]*-->",
        )
    else:
        header_re = re.compile(r"<!--\s*BEGIN\s+auto-generated[^>]*-->")
        footer_re = re.compile(r"<!--\s*END\s+auto-generated[^>]*-->")

    header_match = header_re.search(text)
    if not header_match:
        return text, False

    # The footer must appear AFTER the header.
    footer_match = footer_re.search(text, header_match.end())
    if not footer_match:
        raise ValueError(
            f"BEGIN marker found at position {header_match.start()} but no "
            f"matching END marker for section={section!r}."
        )

    start = header_match.start()
    end = footer_match.end()
    return text[:start] + new_block + text[end:], True


def update_readme_in_place(
    *,
    readme_path: PathLike = REPO_ROOT / "README.md",
    manager: Optional[OutputManager] = None,
    overwrite: Union[str, OverwritePolicy] = OverwritePolicy.OVERWRITE,
    dry_run: bool = False,
    insert_if_missing: bool = False,
) -> dict[str, Any]:
    """Safely update the auto-generated blocks inside ``README.md``.

    Parameters
    ----------
    readme_path:
        Path to the README file (default: ``<repo>/README.md``).
    manager:
        :class:`OutputManager` used for the accompanying fragments written
        to ``output/readme/``.
    overwrite:
        Overwrite policy forwarded to the manager for fragments.
    dry_run:
        If ``True``, only return the diff / plan — nothing is written.
    insert_if_missing:
        If ``True`` and no markers exist in the README, append the blocks
        to the end.  When ``False`` (default), missing markers are an
        error so we never silently modify a hand-curated README.

    Returns
    -------
    dict
        ``{"changed": bool, "written": list[WriteRecord], "readme": Path}``
    """
    if manager is None:
        manager = get_output_manager()
    if overwrite != manager.overwrite:
        manager = OutputManager(
            root=manager.root,
            overwrite=overwrite,
            category_dirs=manager._category_dirs,
            dry_run=dry_run or manager.dry_run,
        )

    readme_path = Path(readme_path)
    if not readme_path.exists():
        raise FileNotFoundError(f"README not found: {readme_path}")

    original = readme_path.read_text(encoding="utf-8")

    # Build the two blocks (with section tags for unambiguous matching).
    nb_header = build_header(section="notebooks")
    nb_footer = build_footer(section="notebooks")
    nb_block = nb_header + build_notebook_index() + nb_footer

    art_header = build_header(section="artefacts")
    art_footer = build_footer(section="artefacts")
    art_block = art_header + build_artefact_index(manager.root) + art_footer

    # Step 1: write companion fragments to output/readme/ (always, even
    # when doing in-place update — the fragments serve as a record).
    written: list[WriteRecord] = []
    if not dry_run:
        written.append(
            manager.save_readme(nb_block, "auto_generated_section_notebooks", ext="md"),
        )
        written.append(
            manager.save_readme(art_block, "auto_generated_section_artefacts", ext="md"),
        )

    # Step 2: replace in the README.
    new_text = original
    changed = False

    for block, section in ((nb_block, "notebooks"), (art_block, "artefacts")):
        try:
            new_text, replaced = _replace_marked_block(
                new_text, block, section=section,
            )
        except ValueError:
            if insert_if_missing:
                new_text = new_text.rstrip() + "\n\n" + block
                replaced = True
            else:
                raise
        else:
            if not replaced and insert_if_missing:
                new_text = new_text.rstrip() + "\n\n" + block
                replaced = True
        if replaced:
            changed = True

    if changed and not dry_run:
        # Keep trailing newline tidy.
        if not new_text.endswith("\n"):
            new_text += "\n"
        readme_path.write_text(new_text, encoding="utf-8")

    return {
        "changed": changed,
        "written": written,
        "readme": readme_path,
    }


# --------------------------------------------------------------------------- #
# Main entry point
# --------------------------------------------------------------------------- #
def generate_readme_section(
    *,
    manager: Optional[OutputManager] = None,
    overwrite: Union[str, OverwritePolicy] = OverwritePolicy.OVERWRITE,
    stem: str = "auto_generated_section",
) -> list[WriteRecord]:
    """Generate the README auto-section and save it via OutputManager.

    Returns
    -------
    list[WriteRecord]
        One record per generated fragment.  Currently two fragments are
        produced:

        - ``notebook_index`` — ordered list of all chapter notebooks.
        - ``artefact_index`` — inventory of files already present under
          ``output/``.

    Both are written to ``output/readme/`` as markdown files.
    """
    if manager is None:
        manager = get_output_manager()
    if overwrite != manager.overwrite:
        manager = OutputManager(
            root=manager.root,
            overwrite=overwrite,
            category_dirs=manager._category_dirs,
            dry_run=manager.dry_run,
        )

    header = build_header()
    footer = build_footer()

    records: list[WriteRecord] = []

    # Notebook index
    nb_md = header + build_notebook_index() + footer
    records.append(
        manager.save_readme(nb_md, f"{stem}_notebooks", ext="md"),
    )

    # Artefact index
    art_md = header + build_artefact_index(manager.root) + footer
    records.append(
        manager.save_readme(art_md, f"{stem}_artefacts", ext="md"),
    )

    return records


if __name__ == "__main__":  # pragma: no cover - CLI
    import argparse

    parser = argparse.ArgumentParser(
        description="Generate README auto-generated sections (fragment or in-place).",
    )
    parser.add_argument(
        "--in-place",
        action="store_true",
        help="Update README.md in place (safe marker replacement).",
    )
    parser.add_argument(
        "--insert-if-missing",
        action="store_true",
        help="Append auto-blocks to the end of README.md when markers are missing.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Do not write anything — just report what would change.",
    )
    parser.add_argument(
        "--readme",
        type=Path,
        default=REPO_ROOT / "README.md",
        help="Path to the README file (default: <repo>/README.md).",
    )
    parser.add_argument(
        "--overwrite",
        choices=[p.value for p in OverwritePolicy],
        default=OverwritePolicy.OVERWRITE.value,
        help="Overwrite policy for output fragments (default: overwrite).",
    )
    args = parser.parse_args()

    mgr = get_output_manager(reset=True, overwrite=args.overwrite, dry_run=args.dry_run)

    if args.in_place:
        result = update_readme_in_place(
            readme_path=args.readme,
            manager=mgr,
            overwrite=args.overwrite,
            dry_run=args.dry_run,
            insert_if_missing=args.insert_if_missing,
        )
        print(f"README {'CHANGED' if result['changed'] else 'UNCHANGED'}: {result['readme']}")
        for rec in result["written"]:
            print(f"  [{rec.status.upper()}] {rec.path}")
    else:
        recs = generate_readme_section(manager=mgr, overwrite=args.overwrite)
        for rec in recs:
            print(f"[{rec.status.upper()}] {rec.path}  ({rec.bytes_written} bytes)")

    print()
    print(mgr.report())
